default:
  tags:
    - docker
    - linux

stages:
  - test
  - deploy
  - sync


include:
- local: '/.gitlab/build-and-test.yml'
#- local: '/.gitlab/deploy-pages.yml'
- local: '/.gitlab/deploy-docker.yml'
- template: Jobs/SAST.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
# - local: '/.gitlab/sync2github.yml'    # Push mirror for github (master)

sast:
  stage: test
